import { BsWhatsapp } from "react-icons/bs";

const products = [
   {
    id: 1 ,
    image: '/creation1.png',
    bestseller: 'Bestsell',
    title: 'Lavender Macarons',
    price: 'N12,000',
    description: 'Infused with organic Provence lavender and filled with a white chocolate ganache.',
    order: 'Order Now',
    icon: <BsWhatsapp />,
    category: 'Macarons',
   },
    {
    id: 2 ,
    image: '/creation2.png',
    version: 'New',
    title: 'Pistachio Tart',
    price: 'N8,000',
    description: 'Roasted pistachio cream with a crunchy praline base and shortcrust pastry.',
    order: 'Order Now',
    icon: <BsWhatsapp />,
    category: 'Tarts',
   },
    {
    id: 3 ,
    image: '/creation3.png',
    title: 'Artisan Croissants',
    price: 'N6,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon: <BsWhatsapp />,
    category: 'Croissants',
   },
    {
    id: 4 ,
    image: '/seasonal1.png',
    title: 'Pistachio Galette',
    price: 'N7,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Seasonal',
   },
    {
    id: 5 ,
    image: '/macaron1.png',
    title: 'Lavender & Honey',
    price: 'N13,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Macarons',
   },
    {
    id: 6 ,
    image: '/tarts1.png',
    title: 'Lemon Meringue',
    price: 'N16,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Tarts',
   },
   {
    id: 7 ,
    image: '/corissant1.png',
    bestseller: 'Bestsell',
    title: 'PAIN AU CHOCOLAT',
    price: 'N14,000',
    description: 'Infused with organic Provence lavender and filled with a white chocolate ganache.',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Croissants',
   },
    {
    id: 8 ,
    image: '/seasonal2.png',
    version: 'New',
    title: 'Winter Truffle Box',
    price: 'N5,000',
    description: 'Roasted pistachio cream with a crunchy praline base and shortcrust pastry.',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Seasonal',
   },
   {
    id: 9 ,
    image: '/macaron2.png',
    title: 'Salted Caramel',
    price: 'N20,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Macarons',
   },
   {
    id: 10 ,
    image: '/tarts2.png',
    title: 'Chocolate Ganache',
    price: 'N15,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Tarts',
   },
   {
    id: 11 ,
    image: '/corissant2.png',
    title: 'BERRY MASCARPONE',
    price: 'N17,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Croissants',
   },
   {
    id: 12 ,
    image: '/seasonal3.png',
    bestseller: 'Bestsell',
    title: 'Holiday Spice Cake',
    price: 'N19,000',
    description: 'Infused with organic Provence lavender and filled with a white chocolate ganache.',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Seasonal',
   },
   {
    id: 13 ,
    image: '/macaron3.png',
    title: 'Earl Grey',
    price: 'N20,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Macarons',
   },
   {
    id: 14 ,
    image: '/tarts3.png',
    title: 'Wild Berry',
    price: 'N15,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Tarts',
   },
   {
    id: 15 ,
    image: '/corissant3.png',
    title: 'PISTACHIO ROSE',
    price: 'N17,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Croissants',
   },
   {
    id: 16 ,
    image: '/seasonal4.png',
    bestseller: 'Bestsell',
    title: 'Afternoon Tea Set',
    price: 'N19,000',
    description: 'Infused with organic Provence lavender and filled with a white chocolate ganache.',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Seasonal',
   },
   {
    id: 17 ,
    image: '/macaron4.png',
    title: 'Rose Petal',
    price: 'N20,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Macarons',
   },
   {
    id: 18 ,
    image: '/tarts4.png',
    title: 'Salted Caramel',
    price: 'N15,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Tarts',
   },
   {
    id: 19 ,
    image: '/corissant4.png',
    title: 'Artisan Croissants',
    price: 'N17,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Croissants',
   },
   {
    id: 20 ,
    image: '/seasonal1.png',
    bestseller: 'Bestsell',
    title: 'Pistachio Galette',
    price: 'N19,000',
    description: 'Infused with organic Provence lavender and filled with a white chocolate ganache.',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Seasonal',
   },
   {
    id: 21 ,
    image: '/tarts5.png',
    title: 'Almond Pear',
    price: 'N15,000',
    description: 'Authentic 72-hour fermented dough with high- fat French butter for ultimate flakiness..',
    order: 'Order Now',
    icon:  <BsWhatsapp />,
    category: 'Tarts',
   },

]

export default products;